source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

inhibit_all_warnings!

target 'RSKGrowingTextViewExample' do
  pod 'RSKKeyboardAnimationObserver', '1.0.0'
  pod 'RSKPlaceholderTextView', '6.1.0'
end
